# First print your name in the cell below then save this file. (or something nice about your instructor)

In [1]:
# In this cell print your name
print('anything')

anything

# Data wrangling with Pandas exercise
* For this exercise we will be using the `listings.csv` data file.

In [2]:
import pandas as pd
import numpy as np

# Load in the data file using `pd.read_csv()`

In [3]:
df = pd.read_csv(filepath_or_buffer='data/listings.csv')

In [4]:
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,175,3,48,2019-11-04,0.37,2,365
1,3831,"Whole flr w/private bdrm, bath & kitchen(pls r...",4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,75,1,340,2020-08-01,4.75,1,265
2,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,29,50,2019-12-02,0.37,1,365
3,5136,"Spacious Brooklyn Duplex, Patio + Garden",7378,Rebecca,Brooklyn,Sunset Park,40.66120,-73.99423,Entire home/apt,175,14,1,2014-01-02,0.01,1,295
4,5178,Large Furnished Room Near B'way,8967,Shunichi,Manhattan,Hell's Kitchen,40.76489,-73.98493,Private room,65,2,473,2020-03-15,3.44,1,340

## Exercise 2 - Filtering

Return the following subsets of the dataframe.

1. How many listings are there with a price less than 100? 


2. Find how many listings there are in just Brooklyn.


3. Find how many listings there are in Brooklyn with a price less than 100.


4. Using `.isin()` select anyone that has the host name of Michael, David, John, and Daniel.


5. Create a new column called `adjusted_price` that has $100 added to every listing in Williamsburg.  The prices for all other listings should be the same as the were before. 


6. What % of the rooms are private, and what % of the rooms are shared.  
    * Hint, use `.value_counts()`

In [5]:
# 1. How many listings are there with a price less than 100? 

df[df['price'] < 100]['price'].sum()

1442248

In [6]:
# 2. Make a new DataFrame of listings in Brooklyn named `df_bk` 
# and find how many listings in just Brooklyn.

df_bk =df[df['neighbourhood_group'] == 'Brooklyn']
df_bk.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
1,3831,"Whole flr w/private bdrm, bath & kitchen(pls r...",4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,75,1,340,2020-08-01,4.75,1,265
2,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,29,50,2019-12-02,0.37,1,365
3,5136,"Spacious Brooklyn Duplex, Patio + Garden",7378,Rebecca,Brooklyn,Sunset Park,40.66120,-73.99423,Entire home/apt,175,14,1,2014-01-02,0.01,1,295
8,5803,"Lovely Room 1, Garden, Best Area, Legal rental",9744,Laurie,Brooklyn,South Slope,40.66829,-73.98779,Private room,88,4,180,2020-03-18,1.31,3,344
11,6848,Only 2 stops to Manhattan studio,15991,Allen & Irina,Brooklyn,Williamsburg,40.70837,-73.95352,Entire home/apt,109,2,181,2020-03-16,1.32,1,0

In [7]:
# 3. Find how many listings there are in Brooklyn with a price less than 100.


df_bk[df_bk['price']<100]['price'].sum()

647433

In [8]:
# 4. Using `.isin()` select anyone that has the host name of Michael, David, John, and Daniel.
# How many total are there that have those names
names = ["Michael", "David", "John", "Daniel"]

cond = df.host_name.isin(names)

df[cond]['host_name'].value_counts()

Michael    387
David      348
John       270
Daniel     253
Name: host_name, dtype: int64

In [9]:
# 5. Create a new column called `adjusted_price` that has $100 added to every listing in Williamsburg.  
# The prices for all other listings should be the same as the were before. 
df['adjusted_price'] = np.where(df["neighbourhood"] == "Williamsburg", df['price'] + 100, df['price'])
df.head(10)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,adjusted_price
0,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,175,3,48,2019-11-04,0.37,2,365,175
1,3831,"Whole flr w/private bdrm, bath & kitchen(pls r...",4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,75,1,340,2020-08-01,4.75,1,265,75
2,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,29,50,2019-12-02,0.37,1,365,60
3,5136,"Spacious Brooklyn Duplex, Patio + Garden",7378,Rebecca,Brooklyn,Sunset Park,40.66120,-73.99423,Entire home/apt,175,14,1,2014-01-02,0.01,1,295,175
4,5178,Large Furnished Room Near B'way,8967,Shunichi,Manhattan,Hell's Kitchen,40.76489,-73.98493,Private room,65,2,473,2020-03-15,3.44,1,340,65
5,5203,Cozy Clean Guest Room - Family Apt,7490,MaryEllen,Manhattan,Upper West Side,40.80178,-73.96723,Private room,75,2,118,2017-07-21,0.89,1,0,75
6,5238,Cute & Cozy Lower East Side 1 bdrm,7549,Ben,Manhattan,Chinatown,40.71344,-73.99037,Entire home/apt,140,1,161,2019-07-29,1.21,4,274,140
7,5552,Spacious river view in the West Village,8380,Maria,Manhattan,West Village,40.73552,-74.01042,Entire home/apt,160,3,66,2019-08-10,0.49,1,178,160
8,5803,"Lovely Room 1, Garden, Best Area, Legal rental",9744,Laurie,Brooklyn,South Slope,40.66829,-73.98779,Private room,88,4,180,2020-03-18,1.31,3,344,88
9,6021,Wonderful Guest Bedroom in Manhattan CENTRAL PARK,11528,Claudio,Manhattan,Upper West Side,40.79826,-73.96113,Private room,85,2,123,2019-12-09,0.90,1,365,85

In [10]:
df['room_type'].unique()

array(['Entire home/apt', 'Private room', 'Shared room', 'Hotel room'],
      dtype=object)

In [11]:
# 6. What % of the rooms are private, and what % of the rooms are shared.  

(df['room_type'] == 'Private room').mean()*100
(df['room_type'] == 'Shared room').mean()*100

2.12134889419047

# Exercise 3 - Grouping

1. Using `groupby`, count how many listings are in each neighbourhood_group.


2. Using `groupby`, find the mean price for each of the neighbourhood_groups. 


3. Using `groupby` and `.agg()`, find the min and max price for each of the neighbourhood_groups. 


4. Using `groupby`, find the median price for each room type in each neighbourhood_group.


5. Using `groupby` and `.agg()`, find the count, min, max, mean, median, and std of the prices for each room type in each neighbourhood_group.

In [12]:
# 1. Using `groupby`, count how many listings are in each neighbourhood_group.

group_gb = df.groupby('neighbourhood_group')

group_gb.size()

neighbourhood_group
Bronx             1183
Brooklyn         18632
Manhattan        20580
Queens            5791
Staten Island      341
dtype: int64

In [13]:
# 2. Using `groupby`, find the mean price for each of the neighbourhood_groups. 

group_gb['price'].mean()

neighbourhood_group
Bronx             92.751479
Brooklyn         120.225258
Manhattan        191.880466
Queens            99.754965
Staten Island    110.947214
Name: price, dtype: float64

In [14]:
# 2.5. Using `groupby`, find the mean price for each room_type. 

gb_room = df.groupby('room_type')

gb_room['price'].mean()

room_type
Entire home/apt    199.395950
Hotel room         275.015075
Private room        91.453084
Shared room         87.063830
Name: price, dtype: float64

In [15]:
# 3. Using `groupby` and `.agg()`, find the min and max price for each of the neighbourhood_groups. 


group_gb['price'].agg(['min', 'max'])

                     min    max
neighbourhood_group
Bronx                 16   1404
Brooklyn               0  10000
Manhattan              0  10000
Queens                 0  10000
Staten Island         19   1200

In [16]:
# 4. Using `groupby`, find the mean price for each room_type in each neighbourhood_group.

gb_list = ['neighbourhood_group','room_type']

gb = df.groupby(gb_list)

gb['price'].mean()

neighbourhood_group  room_type
Bronx                Entire home/apt    138.004819
                     Private room        68.419668
                     Shared room         66.391304
Brooklyn             Entire home/apt    171.587687
                     Hotel room         147.300000
                     Private room        71.291189
                     Shared room         57.870091
Manhattan            Entire home/apt    231.335572
                     Hotel room         292.515670
                     Private room       128.277069
                     Shared room        111.735084
Queens               Entire home/apt    150.168900
                     Hotel room         139.058824
                     Private room        69.972564
                     Shared room         89.891892
Staten Island        Entire home/apt    151.720930
                     Private room        70.312883
                     Shared room         46.000000
Name: price, dtype: float64

In [17]:
# 5. Using `groupby` and `.agg()`, find the count, min, max, mean, median, and std of the prices 
# for each room type in each neighbourhood_group.


gb['price'].agg(['min', 'max', 'mean', 'median', 'std'])

                                     min    max        mean  median  \
neighbourhood_group room_type
Bronx               Entire home/apt   25   1404  138.004819   103.0
                    Private room      16    700   68.419668    55.0
                    Shared room       20    800   66.391304    44.0
Brooklyn            Entire home/apt   20  10000  171.587687   135.0
                    Hotel room         0    399  147.300000   129.0
                    Private room      10   2500   71.291189    60.0
                    Shared room       15   1500   57.870091    36.0
Manhattan           Entire home/apt    0  10000  231.335572   165.0
                    Hotel room         0   2211  292.515670   210.0
                    Private room      10  10000  128.277069    80.0
                    Shared room       10  10000  111.735084    60.0
Queens              Entire home/apt   10  10000  150.168900   115.0
                    Hotel room         0    249  139.058824   149.0
                    Private room      18   9000   69.972564    55.0
                    Shared room       14   3000   89.891892    40.0
Staten Island       Entire home/apt   39   1200  151.720930   111.0
                    Private room      20    800   70.312883    55.0
                    Shared room       19     82   46.000000    38.0

                                            std
neighbourhood_group room_type
Bronx               Entire home/apt  126.032106
                    Private room      57.337866
                    Shared room      114.442703
Brooklyn            Entire home/apt  236.732843
                    Hotel room        91.153206
                    Private room      69.023165
                    Shared room       92.217618
Manhattan           Entire home/apt  410.306439
                    Hotel room       315.924085
                    Private room     448.677306
                    Shared room      502.728868
Queens              Entire home/apt  252.606739
                    Hotel room        50.743806
                    Private room     163.814468
                    Shared room      275.675158
Staten Island       Entire home/apt  147.518392
                    Private room      70.759593
                    Shared room       28.446441

# Join and file saving.
1. Load the `prices.csv` and the `n_listings.csv`


2. Do join that keeps all the records for each table.
    * Neighbourhood groups should include ['Bronx', 'Brooklyn', 'Manhattan', 'Queens', 'Staten Island',
       'LongIsland']
       
       
3. Save your joined csv as `joined.csv`


4. Load your saved table and see if it looks the same or different that the DataFrame you used to create it.

In [18]:
# 1. Load the `prices.csv` and the `n_listings.csv`

df_prices = pd.read_csv('data/prices.csv')
df_prices

  neighbourhood_group   mean_price
0               Bronx    92.751479
1            Brooklyn   120.225258
2           Manhattan   191.880466
3              Queens    99.754965
4       Staten Island   110.947214

In [19]:
df_listings = pd.read_csv('data/listings.csv')
df_listings

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,175,3,48,2019-11-04,0.37,2,365
1,3831,"Whole flr w/private bdrm, bath & kitchen(pls r...",4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,75,1,340,2020-08-01,4.75,1,265
2,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,29,50,2019-12-02,0.37,1,365
3,5136,"Spacious Brooklyn Duplex, Patio + Garden",7378,Rebecca,Brooklyn,Sunset Park,40.66120,-73.99423,Entire home/apt,175,14,1,2014-01-02,0.01,1,295
4,5178,Large Furnished Room Near B'way,8967,Shunichi,Manhattan,Hell's Kitchen,40.76489,-73.98493,Private room,65,2,473,2020-03-15,3.44,1,340
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46522,44807522,Designer Gramercy Studio Townhouse by UNSQ,12941925,Brian,Manhattan,Gramercy,40.73433,-73.98383,Entire home/apt,145,7,0,NaN,NaN,1,164
46523,44807786,Cozy & comfy apt in the heart of Inwood Manhattan,284790520,Salar,Manhattan,Washington Heights,40.85820,-73.92733,Entire home/apt,87,6,0,NaN,NaN,2,85
46524,44811717,Comfortable safe environment 24hr security camera,362453686,Nicole,Brooklyn,East Flatbush,40.65399,-73.93287,Private room,59,3,0,NaN,NaN,1,90
46525,44814944,Upper West Side studio 86th Street,4039777,Fernando,Manhattan,Upper West Side,40.78731,-73.97029,Entire home/apt,80,30,0,NaN,NaN,1,113
46526,44818009,"5MIN D/N trains, NEAR THE BEACH, 50â€™ TO MANHATTAN",48098268,Marina,Brooklyn,Gravesend,40.59945,-73.98209,Private room,66,1,0,NaN,NaN,1,38

In [20]:
# 2. Do join that keeps all the records for each table.
df_joined = pd.merge(df_prices, df_listings, how = 'outer')

df_joined

,neighbourhood_group,mean_price,id,name,host_id,host_name,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,Bronx,92.751479,44096,Room with a View,190409,Waundell,Highbridge,40.83232,-73.93184,Private room,50,1,277,2020-02-25,2.29,3,364
1,Bronx,92.751479,45935,Room in Beautiful Townhouse.,204586,L,Port Morris,40.80640,-73.92395,Private room,60,3,0,NaN,NaN,1,83
2,Bronx,92.751479,54626,Cozy bedroom by Yankee Stadium,190409,Waundell,Highbridge,40.83075,-73.93058,Private room,55,1,181,2020-03-06,1.66,3,364
3,Bronx,92.751479,63588,LL3,295128,Carol Gloria,Clason Point,40.81309,-73.85514,Private room,89,2,0,NaN,NaN,7,270
4,Bronx,92.751479,63610,DOMINIQUE'S NY mini efficiency pad* SANITIZED*...,310670,Vie,Eastchester,40.88100,-73.83511,Entire home/apt,102,2,44,2020-06-28,0.49,9,363
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46522,Staten Island,110.947214,44288244,Huge Private Room/Suite @ Ferry.,117492425,Dine,St. George,40.64602,-74.07896,Private room,49,4,0,NaN,NaN,8,365
46523,Staten Island,110.947214,44322571,Rosebank Townhome,299411542,Karen,Clifton,40.61847,-74.06974,Private room,300,1,0,NaN,NaN,2,179
46524,Staten Island,110.947214,44322911,Oakwood Room,299411542,Karen,Oakwood,40.56436,-74.13019,Private room,150,1,0,NaN,NaN,2,179
46525,Staten Island,110.947214,44415969,Style Home away from home,121399223,Weifeng(Daniel),Tompkinsville,40.63380,-74.08298,Entire home/apt,160,1,1,2020-08-02,1.00,3,365
46526,Staten Island,110.947214,44574046,Home away from home,356621108,Andrew,Howland Hook,40.63348,-74.16950,Entire home/apt,250,1,0,NaN,NaN,1,14

# Extra Credit
Every question below this cell is extra credit and optional.

### 1. (Easy) Explore this new PandasAI Package and tell me what its all about because I've never used it. 
* https://www.youtube.com/watch?v=5w6eZaoDVVk&ab_channel=CodingIsFun  
* See if you can use it on the listings.csv to find out some cool info. or answer some of the questions above.

In [21]:
from pandasai import PandasAI
from pandasai.llm.openai import OpenAI
llm = OpenAI(api_token = 'token')

In [22]:
pandas_ai = PandasAI(llm, conversational = False)

C:\Users\thema\anaconda3\Lib\site-packages\pandasai\__init__.py:145: UserWarning: `PandasAI` (class) is deprecated since v1.0 and will be removed in a future release. Please use `SmartDataframe` instead.
  warnings.warn("`PandasAI` (class) is deprecated since v1.0 and will be removed "

In [23]:
pandas_ai.run(df, prompt = 'which two gfeatures have the highest correlations?')

'Unfortunately, I was not able to answer your question, because of the following error:\n\nYou exceeded your current quota, please check your plan and billing details.\n'

* I ain't poor, I'm just broke

### 2. (Very Easy) Find other cool Panda packages / add ons and show us what they can do well. And how you installed them.

### 3. (Medium) Use the grammys.csv data for the next section of questions.

1. Who was won Album of the Year in 2016?


2. Who won Best Rap Album in 2009?


3. How many awards was Kendrick Lamar nomiated for, and how many did he win...?

In [24]:
df_grammys = pd.read_csv('data/grammys.csv')

In [25]:
df_grammys.head()

,year,category,nominee,workers,winner
0,1959,Album of the Year,The Music from Peter Gunn.,Henry Mancini,True
1,1959,Best Album Cover,Only the Lonely,Frank Sinatra (art director),True
2,1959,Best Arrangement,The Music From Peter Gunn,Henry Mancini (artist/arranger),True
3,1959,Best Classical Performance - Chamber Music (in...,Beethoven: Quartet 130,"The Hollywood String Quartet, Paul Shure (arti...",True
4,1959,Best Classical Performance - Instrumentalist (...,Segovia Golden Jubilee,AndrÃ©s Segovia,True

In [26]:
df_grammys.dtypes

year         int64
category    object
nominee     object
workers     object
winner        bool
dtype: object

In [27]:
df_grammys.shape

(6323, 5)

In [28]:
df_grammys['category'].unique()

array(['Album of the Year', 'Best Album Cover', 'Best Arrangement',
       'Best Classical Performance - Chamber Music (including Chamber Orchestra)',
       'Best Classical Performance - Instrumentalist (other than Concerto Scale Accompaniment)',
       'Best Classical Performance - Instrumentalist (other than concerto-scale accompaniment)',
       'Best Classical Performance - Instrumentalist (with Concerto Scale Accompaniment)',
       'Best Classical Performance - Operatic or Choral',
       'Best Classical Performance - Orchestra',
       'Best Classical Performance - Vocal Soloist (with or without Orchestra)',
       'Best Comedy Performance', 'Best Country & Western Performance',
       'Best Country and Western Performance',
       'Best Engineered Record (Classical)',
       'Best Engineered Record - Non-Classical',
       'Best Instrumental Arrangement', 'Best Instrumental Composition',
       'Best Jazz Performance, Group',
       'Best Jazz Performance, Individual',
       'Best Musical Composition First Recorded and Released in 1958 (over 5 minutes duration)',
       'Best Original Cast Album (Broadway or TV)',
       'Best Performance by a Dance Band',
       'Best Performance by a Vocal Group or Chorus',
       'Best Performance by an Orchestra - for Other Than Dancing',
       'Best Performance, Documentary or Spoken Word',
       'Best R&B Vocal Performance by a Duo or Group',
       'Best Recording for Children', 'Best Rhythm & Blues Performance',
       'Best Sound Track Album, Dramatic Picture Score or Original Cast',
       'Best Soundtrack Album, Dramatic Picture Score or Original Cast',
       'Best Vocal Performance, Female', 'Best Vocal Performance, Male',
       'Record of the Year', 'Song of the Year',
       'Best Album Created For Children',
       'Best Classical Opera Production',
       'Best Classical Performance - Vocal Or Instrumental - Chamber Music',
       'Best Classical Performance- Choral (Including Oratorio)',
       'Best Classical Performance- Concerto Or Instrumental Soloist',
       'Best Classical Performance- Instrumental Soloist Or Duo (Other Than With Orchestral Accompaniment)',
       'Best Classical Performance- Orchestra',
       'Best Classical Performance- Vocal Soloist',
       'Best Comedy Performance - Musical',
       'Best Comedy Performance - Spoken Word',
       'Best Contemporary Classical Composition',
       'Best Engineering Contribution - Classical Recording',
       'Best Engineering Contribution - Novelty Recording',
       'Best Engineering Contribution - Popular Recording',
       'Best Jazz Composition Of More Than Five Minutes Duration',
       'Best Jazz Performance Large Group',
       'Best Jazz Performance Solo or Small Group', 'Best New Artist',
       'Best Performance By A Pop Single Artist',
       'Best Performance by a Band For Dancing',
       'Best Performance by a Chorus (7 Or More Persons)',
       'Best Performance by a Vocal Group (2 To 6)',
       'Best Performance by an Orchestra',
       'Best Performance- Documentary or Spoken Word (Other Than Comedy)',
       'Best Performance- Folk', 'Best Show Album (Original Cast)',
       'Best Soundtrack Album or Recording of Music Score from Motion Picture or Television',
       'Best Soundtrack Album or Recording of Original Cast from a Motion Picture or TV',
       'Best Vocal Performance Album, Female',
       'Best Vocal Performance Album, Male',
       'Best Vocal Performance Single Record Or Track, Female',
       'Best Vocal Performance Single Record or Track, Female',
       'Best Vocal Performance Single Record or Track, Male',
       'Best Spoken Word Album', 'Album Of the Year - Classical',
       'Best Album Cover (Other Than Classical)',
       'Best Album Cover- Classical',
       'Best Classical Performance- Chamber Music',
       'Best Classical Performance- Choral (Other Than Opera)',
       'Best Classical Performance- Instrumental Soloist (With Orchestra)',
       'Best Classical Performance- Instrumental Soloist Or Duo (Without Orchestra)',
       'Best Classical Performance- Vocal Soloist (With or Without Orchestra)',
       'Best Country & Western Recording',
       'Best Documentary or Spoken Word Recording (Other Than Comedy)',
       'Best Engineering Contribution - Novelty', 'Best Folk Recording',
       'Best Gospel Or Other Religious Recording',
       'Best Instrumental Theme Or Instrumental Version of Song',
       'Best Jazz Performance - Large Group (Instrumental)',
       'Best Jazz Performance- Soloist or Small Group (Instrumental)',
       'Best New Artist Of 1961', 'Best Opera Recording',
       'Best Original Cast Show Album', 'Best Original Jazz Composition',
       'Best Performance by a Chorus',
       'Best Performance by a Vocal Group',
       'Best Performance by an Orchestra- For Dancing',
       'Best Rhythm & Blues Recording', 'Best Rock & Roll Recording',
       'Best Solo Vocal Performance, Female',
       'Best Solo Vocal Performance, Male',
       'Best Soundtrack Album or Recording of Original Cast from Motion Picture or Television',
       'Best Soundtrack Album or Recording of Score from Motion Picture or Television',
       'Album of the Year (Other Than Classical)',
       'Best Album Cover- Other Than Classical',
       'Best Background Arrangement (Behind Vocalist Or Instrumentalist)',
       'Best Classical Performance- Instrumental Soloist Or Soloists (With Orchestra)',
       'Best Contemporary Composition',
       'Best Documentary, Spoken Word, or Drama Recording (Other Than Comedy)',
       'Best Engineered Recording - Classical',
       'Best Engineering Contribution - Other than Novelty and Other Than Classical',
       'Best Instrumental Theme',
       'Best Jazz Performance- Large Group (Instrumental)',
       'Best New Artist Of 1962',
       'Best Performance by an Orchestra or Instrumentalist with Orchestra- Primarily Not Jazz Or For Dancing',
       'Best Album Notes',
       'Best Classical Composition By A Contemporary Composer',
       'Best Engineered Recording- Classical',
       'Best Engineered Recording- Other than Classical',
       'Best Engineered Recording- Special or Novel Effects',
       'Best Gospel Or Other Religious Recording (Musical)',
       'Best Instrumental Jazz Performance- Large Group',
       'Best Instrumental Jazz Performance- Soloist or Small Group',
       'Best New Artist Of 1963',
       'Best Original Score from a Motion Picture or Television Show',
       'Best Score From An Original Cast Show Album',
       'Classical Album Of the Year',
       'Most Promising New Classical Recording Artist',
       'Album of the Year -- Classical',
       'Best Accompaniment Arrangement for Vocalist(s) or Instrumentalist(s)',
       'Best Chamber Music Performance - Vocal',
       'Best Chamber Performance - Instrumental',
       'Best Choral Performance (other than opera)',
       'Best Composition by a Contemporary Composer',
       'Best Country & Western Album', 'Best Country & Western Single',
       'Best Country & Western Song',
       'Best Country & Western Vocal Performance - Female',
       'Best Country & Western Vocal Performance - Male',
       'Best Documentary, Spoken Word or Drama Recording (other than comedy)',
       'Best Engineered Recording',
       'Best Engineered Recording - Non-Classical',
       'Best Engineered Recording - Special or Novel Effects',
       'Best Gospel or Other Religious Recording (Musical)',
       'Best Instrumental Composition (other than jazz)',
       'Best Instrumental Jazz Performance - Large Group or Soloist with Large Group',
       'Best Instrumental Jazz Performance - Small Group or Soloist with Small Group',
       'Best Instrumental Performance - Non-Jazz',
       'Best Original Score Written for a Motion Picture or Television Show',
       'Best Performance - Instrumental Soloist or Soloists (with orchestra)',
       'Best Performance - Instrumental Soloist or Soloists (without orchestra)',
       'Best Performance - Orchestra',
       'Best Score From an Original Cast Show Album',
       'Best Vocal Soloist Performance (with or without orchestra)',
       'Best Contemporary (R&R)  Vocal Performance, Male',
       'Album of the Year - Classical', 'Best Album Cover - Graphic Arts',
       'Best Album Cover - Photography',
       'Best Arrangement Accompanying a Vocalist or Instrumentalist',
       'Best Classical Chamber Music Performance - Instrumental or Vocal',
       'Best Classical Choral Performance (other than opera)',
       'Best Classical Performance - Instrumental Soloist or Soloists (with orchestra)',
       'Best Classical Performance - Instrumental Soloist or Soloists (without orchestra)',
       'Best Classical Vocal Soloist Performance',
       'Best Composition by a Contemporary Classical Composer',
       'Best Contemporary (R&R) Performance - Group (Vocal or Instrumental)',
       'Best Contemporary (R&R) Single',
       'Best Contemporary (R&R) Vocal Performance - Female',
       'Best Contemporary (R&R) Vocal Performance - Male',
       'Best Engineered Recording, Classical',
       'Best Instrumental Jazz Performance - Small Group or Soloist With Small Group',
       'Best Instrumental Performance, Non-Jazz',
       'Best Spoken Word or Drama Recording',
       'Best Album Cover, Photography',
       'Best Chamber Music Performance - Instrumental or Vocal',
       'Best Classical Performance - Instrumental Soloist or Soloists (with or without orchestra)',
       'Best Classical Vocal Soloist Performance (with or without orchestra)',
       'Best Contemporary (R&R) Group Performance, Vocal or Instrumental',
       'Best Contemporary (R&R) Recording',
       'Best Contemporary (R&R) Solo Vocal Performance - Male or Female',
       'Best Country & Western Vocal Performance, Male',
       'Best Instrumental Jazz Performance - Group or Soloist with Group',
       'Best Instrumental Performance (Other Than Jazz)',
       'Best Rhythm & Blues Group Performance, Vocal or Instrumental',
       'Best Rhythm & Blues Solo Vocal Performance, Male or Female',
       'Best Sacred Performance', 'Best Sacred Recording (Musical)',
       'Best Spoken Word, Documentary or Drama Recording',
       'Best Album Cover, Graphic Arts', 'Album of the Year, Classical',
       'Best Arrangement Accompanying Vocalist(s) or Instrumentalist(s)',
       'Best Chamber Music Performance', 'Best Comedy Recording',
       'Best Contemporary Album',
       'Best Contemporary Female Solo Vocal Performance',
       'Best Contemporary Group Performance (Vocal or Instrumental)',
       'Best Contemporary Male Solo Vocal Performance',
       'Best Contemporary Single',
       'Best Country & Western Performance Duet, Trio or Group (Vocal or Instrumental)',
       'Best Country & Western Solo Vocal Performance, Female',
       'Best Country & Western Solo Vocal Performance, Male',
       'Best Folk Performance', 'Best Gospel Performance',
       'Best Instrumental Jazz Performance, Large Group or Soloist with Large Group',
       'Best Instrumental Jazz Performance, Small Group or Soloist With Small Group',
       'Best Instrumental Performance',
       'Best Original Score Written for a Motion Picture or a Television Show',
       'Best Rhythm & Blues Solo Vocal Performance, Female',
       'Best Rhythm & Blues Solo Vocal Performance, Male',
       'Best Arrangement Accompanying Vocalist(s)',
       'Best Contemporary Pop Performance - Vocal Duo or Group',
       'Best Contemporary Pop Performance, Chorus',
       'Best Contemporary Pop Performance, Instrumental',
       'Best Contemporary Pop Vocal Performance, Female',
       'Best Contemporary Pop Vocal Performance, Male',
       'Best Country Performance, Duo or Group - Vocal or Instrumental',
       'Best Country Song', 'Best Country Vocal Performance, Female',
       'Best Country Vocal Performance, Male',
       'Best Engineered Recording, Non-Classical',
       'Best New Artist of the Year',
       'Best Original Score Written for a Motion Picture',
       'Best Original Score Written for a Motion Picture or a Television Special',
       'Best Performance - Instrumental Soloist or Soloists (with or without orchestra)',
       'Best Rhythm & Blues Performance by a Duo or Group, Vocal or Instrumental',
       'Best Rhythm & Blues Song',
       'Best Rhythm & Blues Vocal Performance, Female',
       'Best Rhythm & Blues Vocal Performance, Male',
       'Best Soul Gospel Performance', 'Best Spoken Word Recording',
       'Best Vocal Soloist Performance',
       'Best Country Vocal Performance by a Duo or Group',
       'Best Choral Performance, Classical',
       'Best Classical Performance, Instrumental Soloist or Soloists (with or without Orchestra)',
       'Best Classical Performance, Orchestra',
       'Best Contemporary Instrumental Performance',
       'Best Contemporary Performance by a Chorus',
       'Best Contemporary Song',
       'Best Contemporary Vocal Performance by a Group',
       'Best Contemporary Vocal Performance, Female',
       'Best Contemporary Vocal Performance, Male',
       'Best Country Instrumental Performance',
       'Best Instrumental Jazz Performance, Small Group or Soloist with Small Group',
       'Best R&B Instrumental Performance', 'Best R&B Song',
       'Best R&B Vocal Performance, Female',
       'Best R&B Vocal Performance, Male',
       'Best Score from an Original Cast Show Album',
       'Best Vocal Soloist Performance, Classical',
       'Best Choral Performance',
       'Best Contemporary Vocal Performance by a Duo, Group or Chorus',
       'Best Ethnic or Traditional Recording (Including Traditional Blues)',
       'Best Jazz Performance, Large Group or Soloist with Large Group',
       'Best Jazz Performance, Small Group or Soloist with Small Group',
       'Best R&B Performance by a Duo or Group, Vocal or Instrumental',
       'Lifetime Achievement Award',
       'Best Classical Performance, Instrumental Soloist or Soloists (with Orchestra)',
       'Best Classical Performance, Instrumental Soloist or Soloists (without Orchestra)',
       'Best Ethnic or Traditional Recording',
       'Best Jazz Performance by a Big Band',
       'Best Jazz Performance by a Group',
       'Best Jazz Performance by a Soloist',
       'Best Pop Instrumental Performance',
       'Best Pop Vocal Performance by a Duo or Group',
       'Best Pop Vocal Performance, Female',
       'Best Pop Vocal Performance, Male',
       'Best R&B Vocal Performance by a Group',
       'Best Album Notes, Classical', 'Best Classical Album',
       'Best Classical Performance Instrumental Soloist or Soloists (with Orchestra)',
       'Best Classical Performance Instrumental Soloist or Soloists (without Orchestra)',
       'Best Inspirational Performance',
       'Best Pop Instrumental Performance by an Arranger, Composer, Orchestra and/or Choral Leader',
       'Best Pop Instrumental Performance by an Instrumental Performer',
       'Best Pop Vocal Performance by a Duo, Group or Chorus',
       'Best R&B Vocal Performance by a Duo, Group or Chorus',
       'Album of Best Original Score Written for a Motion Picture or a Television Special',
       'Best Album Package',
       'Best Score from the Original Cast Show Album',
       'Album of Best Original Score Written for a Motion Picture',
       'Best Album Notes - Classical',
       'Best Arrangement Accompanying Vocalists',
       'Best Choral Performance, Classical (other than opera)',
       'Best Classical Performance Instrumental Soloist or Soloists (with orchestra)',
       'Best Classical Performance Instrumental Soloist or Soloists (without orchestra)',
       'Best Gospel Performance (other than soul gospel)',
       'Best Inspirational Performance (non-classical)',
       'Best Producer of the Year',
       'Best Country Vocal Performance - Female',
       'Album of Best Original Score Written for a Motion Picture or Television Special',
       'BEST ARRANGEMENT ACCOMPANYING VOCALIST', 'Best Cast Show Album',
       'Best Jazz Performance BY a Soloist', 'Best Latin Recording',
       'Best Country Vocal Performance - Male',
       'Best Album of Original Score Written for a Motion Picture or Television Special',
       'Best Arrangement for Voices (duo, group or chorus)',
       'Best Classical Orchestral Performance',
       'Best Classical Performance, Instrumental Soloist or Soloists (with orchestra)',
       'Best Classical Performance, Instrumental Soloist or Soloists (without orchestra)',
       'Best Jazz Performance by a Soloist (instrumental)',
       'Best Jazz Vocal Performance',
       'Best Album of Original Score written for a Motion Picture or Television Special',
       'Best Arrangement for Voices',
       'Best Gospel Performance, Contemporary or Insprirational',
       'Best Gospel Performance, Traditional',
       'Best Pop Instrumental Recording',
       'Best Pop Vocal Performance by a Group',
       'Best R&B Vocal Performance - Female',
       'Best Soul Gospel Performance, Contemporary',
       'Best Soul Gospel Performance, Traditional',
       'Producer of the Year', 'Best Pop Vocal Performance - Female',
       'Best Album of Original Score Written for a Motion Picture or a Television Special',
       'Best Arrangement Accompanying Vocal(s)',
       'Best Classical Performance, Instrumental Soloist(s) (with orchestra)',
       'Best Classical Performance, Instrumental Soloist(s) (without orchestra)',
       'Best Gospel Performance, Contemporary or Inspirational',
       'Best Historical Repackage Album',
       'Best Jazz Instrumental Performance, Big Band',
       'Best Jazz Instrumental Performance, Group',
       'Best Jazz Instrumental Performance, Soloist',
       'Best Rock Vocal Performance - Female', 'Best Disco Recording',
       'Best Arrangement Accompanying Vocals',
       'Best Classical Orchestral Recording',
       'Best Country Performance by a Duo or Group with Vocal',
       'Best Historical Reissue Album',
       'Best Jazz Fusion Performance, Vocal or Instrumental',
       'Best Rock Instrumental Performance',
       'Best Rock Vocal Performance by a Duo or Group',
       'Best Rock Vocal Performance, Female',
       'Best Rock Vocal Performance, Male',
       'Classical Producer of the Year',
       'Best Ethnic or Traditional Folk Recording',
       'Best Jazz Vocal Performance, Female',
       'Best Jazz Vocal Performance, Male',
       'Best Pop Performance by a Duo or Group with Vocal',
       'Best R&B Performance by a Duo or Group with Vocal',
       'Best Rock Performance by a Duo or Group with Vocal',
       'Producer of the Year (Non-Classical)',
       'Best Arrangement On An Instrumental Recording',
       'Best Historical Album',
       'Best Instrumental Arrangement Accompanying Vocal(s)',
       'Best Jazz Vocal Performance, Duo or Group',
       'Best Vocal Arrangement for Two or More Voices',
       'Video Of The Year',
       'Best Classical Performance, Instrumental Soloist (with orchestra)',
       'Best Gospel Performance, Contemporary',
       'Best Orchestral Performance', 'Best Traditional Blues Recording',
       'Best Arrangement on an Instrumental',
       'Best Classical Performance â€“ Instrumental Soloist or Soloists (with orchestra)',
       'Best Classical Performance â€“ Instrumental Soloist or Soloists (without orchestra)',
       'Best Gospel Performance by a Duo or Group',
       'Best Gospel Performance, Female', 'Best Gospel Performance, Male',
       'Best Latin Pop Performance', 'Best Mexican-American Performance',
       'Best New Country Song', 'Best Orchestral Recording',
       'Best Soul Gospel Performance by a Duo or Group',
       'Best Soul Gospel Performance, Female',
       'Best Soul Gospel Performance, Male',
       'Best Spoken Word or Non-musical Recording',
       'Best Tropical Latin Performance', 'Best Video Album',

In [29]:
aoty_2016 = df_grammys.loc[(df_grammys['year'] == 2016) & (df_grammys['winner'] == True) & (df_grammys['category'] == "Album of the Year"), 'nominee'].values[0]
aoty_2016

'1989.'

In [30]:
best_rap = df_grammys.loc[(df_grammys['year'] == 2009) & (df_grammys['winner'] == True) & (df_grammys['category'] == "Best Rap Album"), 'nominee'].values[0]
best_rap

'Tha Carter III'

In [31]:
maybe_goat = (df_grammys['nominee'] == 'Kendrick Lamar').sum()
maybe_goat

kendrick = df_grammys['nominee'].str.contains('Kendrick', na = False, case = True)
kendrick_df = df_grammys[kendrick]
kendrick_df

,year,category,nominee,workers,winner
5246,2014,Best New Artist,Kendrick Lamar,NaN,False
5965,2018,Best Music Video,Kendrick Lamar: Humble.,"Jason Baum (Producer), Nathan Scherrer (Produc...",True

In [32]:
kendrick_df[kendrick_df['winner'] == True]

,year,category,nominee,workers,winner
5965,2018,Best Music Video,Kendrick Lamar: Humble.,"Jason Baum (Producer), Nathan Scherrer (Produc...",True

### (Hard) Load the Game Logs for 2022 and add the column names using a dictionary.  
* [Link to the data page](https://www.retrosheet.org/gamelogs/)
* [Link to the column names](https://procatinator.com/)
* haha, gotta find them yourself!

In [33]:
game_df = pd.read_csv(r'C:\Users\thema\my-fork-2023-fall-data-science-fridays\Week-01-Pandas\retrosheet2022.txt')

In [39]:
column_list = game_df.columns.tolist()
len(column_list)

161

In [37]:
game_dict = {}
j = 0
for i in column_list:
    game_dict[i] = j
    j += 1
game_dict

{'20220407': 0,
 '0': 1,
 'Thu': 2,
 'SDN': 3,
 'NL': 4,
 '1': 5,
 'ARI': 6,
 'NL.1': 7,
 '1.1': 8,
 '2': 9,
 '4': 10,
 '51': 11,
 'N': 12,
 'Unnamed: 13': 13,
 'Unnamed: 14': 14,
 'Unnamed: 15': 15,
 'PHO01': 16,
 '35508': 17,
 '198': 18,
 '001100000': 19,
 '000000004': 20,
 '29': 21,
 '4.1': 22,
 '1.2': 23,
 '0.1': 24,
 '0.2': 25,
 '2.1': 26,
 '0.3': 27,
 '0.4': 28,
 '0.5': 29,
 '7': 30,
 '0.6': 31,
 '5': 32,
 '1.3': 33,
 '0.7': 34,
 '2.2': 35,
 '0.8': 36,
 '7.1': 37,
 '5.1': 38,
 '4.2': 39,
 '4.3': 40,
 '2.3': 41,
 '0.9': 42,
 '24': 43,
 '8': 44,
 '0.10': 45,
 '0.11': 46,
 '1.4': 47,
 '0.12': 48,
 '26': 49,
 '3': 50,
 '0.13': 51,
 '0.14': 52,
 '1.5': 53,
 '3.1': 54,
 '0.15': 55,
 '0.16': 56,
 '1.6': 57,
 '7.2': 58,
 '0.17': 59,
 '6': 60,
 '0.18': 61,
 '0.19': 62,
 '1.7': 63,
 '0.20': 64,
 '6.1': 65,
 '6.2': 66,
 '2.4': 67,
 '2.5': 68,
 '0.21': 69,
 '0.22': 70,
 '27': 71,
 '9': 72,
 '0.23': 73,
 '0.24': 74,
 '2.6': 75,
 '0.25': 76,
 'vanol901': 77,
 'Larry Vanover': 78,
 'belld901': 79,
 'Dan Bellino': 80,
 'barbs901': 81,
 'Sean Barber': 82,
 'valej901': 83,
 'Junior Valentine': 84,
 'Unnamed: 85': 85,
 '(none)': 86,
 'Unnamed: 87': 87,
 '(none).1': 88,
 'melvb001': 89,
 'Bob Melvin': 90,
 'lovut001': 91,
 'Tony Lovullo': 92,
 'mantj002': 93,
 'Joe Mantiply': 94,
 'suarr002': 95,
 'Robert Suarez': 96,
 'Unnamed: 97': 97,
 '(none).2': 98,
 'beers001': 99,
 'Seth Beer': 100,
 'darvy001': 101,
 'Yu Darvish': 102,
 'bumgm001': 103,
 'Madison Bumgarner': 104,
 'nolaa002': 105,
 'Austin Nola': 106,
 '2.7': 107,
 'machm001': 108,
 'Manny Machado': 109,
 '5.2': 110,
 'cronj001': 111,
 'Jake Cronenworth': 112,
 '4.4': 113,
 'voitl001': 114,
 'Luke Voit': 115,
 '10': 116,
 'myerw001': 117,
 'Wil Myers': 118,
 '9.1': 119,
 'hosme001': 120,
 'Eric Hosmer': 121,
 '3.2': 122,
 'profj001': 123,
 'Jurickson Profar': 124,
 '7.3': 125,
 'kim-h002': 126,
 'Ha-Seong Kim': 127,
 '6.3': 128,
 'grist001': 129,
 'Trent Grisham': 130,
 '8.1': 131,
 'varsd001': 132,
 'Daulton Varsho': 133,
 '8.2': 134,
 'martk001': 135,
 'Ketel Marte': 136,
 '4.5': 137,
 'perad001': 138,
 'David Peralta': 139,
 '7.4': 140,
 'walkc002': 141,
 'Christian Walker': 142,
 '3.3': 143,
 'smitp002': 144,
 'Pavin Smith': 145,
 '9.2': 146,
 'kellc002': 147,
 'Carson Kelly': 148,
 '2.8': 149,
 'beers001.1': 150,
 'Seth Beer.1': 151,
 '10.1': 152,
 'ellid002': 153,
 'Drew Ellis': 154,
 '5.3': 155,
 'perdg001': 156,
 'Gerardo Perdomo': 157,
 '6.4': 158,
 'Unnamed: 159': 159,
 'Y': 160}

### (Extra Hard) Download the files for the past 5 years into a new folder and add them all into one data frame using pandas, then save that new file.
* Try to not hard code in the file names. We want to do this programmatically because what if we want to add new/more file names in the future.